name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * */3 * *'  # Daily at midnight UTC

jobs:
  update-readme:
    name: Update README with WakaTime Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with WakaTime metrics
        uses: athul/waka-readme@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: manu-cj/manu-cj
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ⬜🟧
          CODE_LANG: JavaScript, Svelte # Languages to prioritize
          TIME_RANGE: last_7_days # Adjust as needed
          LANG_COUNT: 4
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: false
          STOP_AT_OTHER: true
          IGNORED_LANGUAGES: JSON,TOML,BASH # Separate languages by commas
          COMMIT_MESSAGE: "Updated waka-readme graph with new metrics"
          TARGET_BRANCH: main
          TARGET_PATH: README.md
          COMMITTER_NAME: GitHubActionBot
          COMMITTER_EMAIL: action-bot@github.com
          AUTHOR_NAME: manu-cj
          AUTHOR_EMAIL: carenjotje@gmail.com
